spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name:
    username: sa
    password:
#    hikari:
#      auto-commit: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
axon:
  axonserver:
    enabled: false